solute = "solute.pdb"
output = "solvated.pdb"

[solute_lattice]
shape = "hex" # "hex" or "square" solute lattice shape, corresponding to the MolPainter lattice
width = 32 # number of cells along x-axis
height = 16 # number of cells along y-axis
spacing = 8 # length of each cell in angstroms

[solvent_lattice]
spacing = 5 # length of each cell in angstroms
buffer  = 4 # exclusionary distance for adding solvent to lattice in angstroms
lower_z_position = 17 # lower z-limit of the solvent lattice
upper_z_position = 72 # upper z-limit of the solvent lattice

[solvent_molecules]
paths = ['DPPC.pdb', 'W.pdb', 'WF.pdb'] # paths to pdb files of each solvent molecule
numbers = [5, 2500, 250] # number of each molecule in paths to add